apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    server-discovery: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb