apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: minecraft
        env:
          - name: CONNECTION_STRING
            value: "mongodb://mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017/?replicaSet=rs0"
          - name: AUTHENTICATION_DATABASE
            value: admin
          - name: USERNAME
            value: root
          - name: PASSWORD
            value: testee
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
